spring.application.name=backend
server.port=9090

# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/takemybible?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT
jwt.secret=wv4rjKhpjPnn3FZSCfyIHY58bw6Gi6wunKzAb9yyLpu
jwt.expiration-ms=86400000
